In [171]:
from sklearn.datasets import load_boston                   ######### sklearn library's boston house price dataset
      
import numpy as np                                         ####### for matrix operation ,dot,inv,transpose etc.

In [172]:
boston = load_boston()  ########### Loading boston dataset 

In [173]:
print(boston.data.shape)       ######### shape of the dataset  it contains 506 rows and 13 columns

(506, 13)


In [174]:
X = boston.data             ############ transfering data part in variable X for sake of simplicity 

n,m = X.shape               ##########   shape of the dataset
X1 = np.ones((n,1))          #########   creating a vector of size one to append in front of X 

In [175]:
print(X1)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.

In [176]:
x = np.hstack((X1,X))        ############# appending ones in X
x.shape

(506, 14)

In [177]:
Y = boston.target            ############   target variable

In [178]:
Y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [179]:
print(boston.DESCR)              ###############  Description of  dataset 

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [180]:
from sklearn.model_selection import train_test_split               #########  for train,test split
x_train,x_test,y_train,y_test = train_test_split(x,Y,test_size = 0.3,random_state=42)     ######### 0.3 = 30% test data and 70% train data


In [181]:
print(x_train.shape)

(354, 14)


In [182]:
print(x_test.shape)

(152, 14)


In [183]:
import numpy as np

In [184]:
x_trans = np.transpose(x_train)                 ############## the main logic ,first transpose of training data

In [185]:
print(x_trans.shape)

(14, 354)


In [186]:
product = np.dot(x_trans,x_train)     ###### dimension 13 x 13   
                                      #######  multiplication of transposed and original data X

In [187]:
print(product.shape)

(14, 14)


In [188]:
inverse = np.linalg.inv(product)     ##########  inverse of the above result

In [189]:
product = np.dot(inverse,x_trans)     ###### dimension 13 x 13
                                        ######### another multiplication with transpose

In [190]:
product.shape

(14, 354)

In [191]:
result = np.dot(product,y_train)         ######## at last multiplication with y_train

In [192]:
print(result.shape)

(14,)


In [193]:
print(result) ###### these are our b0, b1,b2.......b13

[ 3.16821486e+01 -1.32774155e-01  3.57812335e-02  4.99454423e-02
  3.12127706e+00 -1.54698463e+01  4.04872721e+00 -1.07515901e-02
 -1.38699758e+00  2.42353741e-01 -8.69095363e-03 -9.11917342e-01
  1.19435253e-02 -5.48080157e-01]


In [194]:
y_pred = np.dot(x_test,result)      ######  prdiction using y_pred = x*b_pred


In [195]:
######## finding Root mean squared error

In [196]:
sq = 0
for i in range(152):
    sq += (y_pred[i] - y_test[i])**2
rmse = np.sqrt(sq/n)
print(rmse)

2.543733398709576


In [197]:
########################   Now samething using sklearn Library

In [198]:
from sklearn.linear_model import LinearRegression    ########## for Linear regression

In [199]:
reg = LinearRegression()       

In [200]:
X = boston.data
Y = boston.target
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size = 0.3,random_state=42)


In [201]:
reg.fit(x_train,y_train)   ########  fitting training data

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [202]:
y_pred2 = reg.predict(x_test)      ############ Now prediction using x_test

In [203]:
sq = 0                              ############  Root mean square error 
for i in range(152):
    sq += (y_pred2[i] - y_test[i])**2
rmse = np.sqrt(sq/n)
print(rmse)

2.5437333987095943


In [204]:
reg.intercept_            #########  regeression intercept and we call it b0

31.682148582134243

In [205]:
reg.coef_                 #########  regression coefficients B1,b2,b3,.......b13

array([-1.32774155e-01,  3.57812335e-02,  4.99454423e-02,  3.12127706e+00,
       -1.54698463e+01,  4.04872721e+00, -1.07515901e-02, -1.38699758e+00,
        2.42353741e-01, -8.69095363e-03, -9.11917342e-01,  1.19435253e-02,
       -5.48080157e-01])