In [34]:
import numpy as np   ##### matrix operation such as multiplication, transpose etc.
import pandas as pd  #### datafile handling 

data = pd.read_csv('/home/luffy/Documents/forest_fire_dataset/forestfires.csv')  ##### reading file from system
data.head()  ######## first five rows

X  Y month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area
0  7  5   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0
1  7  4   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0
2  7  4   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0
3  8  6   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0
4  8  6   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0

In [35]:
Y = data.area   ###### seperating data , sending target variable in Y variable
X = data.drop('area',axis=1) ####### after deleting 'area' column ,sending rest of the data in X variable

In [36]:
########### A function to convert categorical data into numerical data

from sklearn.preprocessing import LabelEncoder
def encoding(forest_data):
    le = LabelEncoder()
    for col in forest_data.columns:   ##### loop to iterate over column names so that we can find column of categorical data
        if forest_data[col].dtype =='object':   ##### if data type of column's value is object 
            forest_data[col] = le.fit_transform(forest_data[col])   ###### transforming categorical to numerical and saving the result with the same name
    return forest_data

X = np.array(encoding(X))  ###### function call for encoding

In [37]:
X

array([[ 7. ,  5. ,  7. , ..., 51. ,  6.7,  0. ],
       [ 7. ,  4. , 10. , ..., 33. ,  0.9,  0. ],
       [ 7. ,  4. , 10. , ..., 33. ,  1.3,  0. ],
       ...,
       [ 7. ,  4. ,  1. , ..., 70. ,  6.7,  0. ],
       [ 1. ,  4. ,  1. , ..., 42. ,  4. ,  0. ],
       [ 6. ,  3. ,  9. , ..., 31. ,  4.5,  0. ]])

In [38]:
X_new = np.c_[np.ones((517,1)),X]   ###### Appending ones in front of data set
X_new

array([[ 1. ,  7. ,  5. , ..., 51. ,  6.7,  0. ],
       [ 1. ,  7. ,  4. , ..., 33. ,  0.9,  0. ],
       [ 1. ,  7. ,  4. , ..., 33. ,  1.3,  0. ],
       ...,
       [ 1. ,  7. ,  4. , ..., 70. ,  6.7,  0. ],
       [ 1. ,  1. ,  4. , ..., 42. ,  4. ,  0. ],
       [ 1. ,  6. ,  3. , ..., 31. ,  4.5,  0. ]])

In [39]:
theta_best = np.linalg.inv(X_new.T.dot(X_new)).dot(X_new.T).dot(Y)  ###### Linear regression formula in just one line

In [40]:
theta_best    ####### Parameter , theta0 to theta12

array([-11.5005719 ,   1.88124305,   0.52679701,   0.97328461,
         0.49952683,  -0.10739595,   0.10979519,  -0.01462744,
        -0.6108142 ,   0.98013486,  -0.18491854,   1.78229487,
        -3.25170999])

In [41]:
def cal_cost(theta,X,y):   ###### function to calculate the cost formula :- 1/2m*sum(prediction -Y)^2
    m =len(y)
    predictions = X.dot(theta)
    summation = 0
    for i in range(len(predictions)):
        summation +=((predictions[i]-y[i])**2)
    cost = (1/2*m)*summation
    return cost

############# This is the main function of the programme formula : -theta = theta - (1/m)*learning_rate*(prediction - Y)
def gradient_descent(X,y,theta,learning_rate = 0.01,iterations = 100):
    min_cost = 1e+100  ##### taking too high value to comapre with minimum value of the function
    m = len(y)         #### length of the dataset
    
    for j in range(iterations): #### No. of iteration ,default is 100
        
        predictions = np.dot(X,theta)
        err = np.zeros(len(predictions))   ###### instead of empty error array , i made a zero vector of size of dataset for the sake of convinience
        
        for k in range(len(predictions)):    ###### calculating ERROR
            err[k] = predictions[k]-y[k]
            
            
        pro  = (1/m)*learning_rate*(X.T.dot(err))   ##### half of the formula,  before negative sign
        
        for i in range(len(pro)):       ######## updating theta 
            theta[i]=theta[i]-pro[i]
            
        cost = cal_cost(theta,X,y)      ##### calling function to calculate the cost using updated theta
        
        if cost<min_cost:               ####### comparing cost with minimum if cost is less than min_cost then new minimum cast will be updated
            min_cost = cost
            itera = j+1                 ##### keeping record of iteration where minimum cost was found
            min_theta = theta             ##### keeping record of theta where minimum cost was found
            
        print('iteration :',j+1)
        print('cost',cal_cost(theta,X,y))
        print('theta: ', theta)
        
    return min_cost,itera

In [42]:
lr = 0.00003      ######## laerning rate , taking too low value you can experiment by taking different values
n_iter = 100      ####### no. of iteration 
theta = np.random.randn(13,1)  ###### Random vales of initial theta
min_cost,it = gradient_descent(X_new,Y,theta_best,lr,n_iter)   ##### calling gradient descent function
print("minimum cost :",min_cost)
print('iteration',it)

iteration : 1
cost 527125566.1596501
theta:  [-11.5005719    1.88124305   0.52679701   0.97328461   0.49952683
  -0.10739595   0.10979519  -0.01462744  -0.6108142    0.98013486
  -0.18491854   1.78229487  -3.25170999]
iteration : 2
cost 527125566.1596504
theta:  [-11.5005719    1.88124305   0.52679701   0.97328461   0.49952683
  -0.10739595   0.10979519  -0.01462744  -0.6108142    0.98013486
  -0.18491854   1.78229487  -3.25170999]
iteration : 3
cost 527125566.1596503
theta:  [-11.5005719    1.88124305   0.52679701   0.97328461   0.49952683
  -0.10739595   0.10979519  -0.01462744  -0.6108142    0.98013486
  -0.18491854   1.78229487  -3.25170999]
iteration : 4
cost 527125566.1596498
theta:  [-11.5005719    1.88124305   0.52679701   0.97328461   0.49952683
  -0.10739595   0.10979519  -0.01462744  -0.6108142    0.98013486
  -0.18491854   1.78229487  -3.25170999]
iteration : 5
cost 527125566.15965
theta:  [-11.5005719    1.88124305   0.52679701   0.97328461   0.49952683
  -0.10739595   0.1

iteration : 42
cost 2.3184016256826318e+67
theta:  [3.13325694e+25 1.43604787e+26 1.33087216e+26 1.92573890e+26
 8.73410276e+25 2.86586182e+27 4.09700447e+27 2.05689015e+28
 2.97534225e+26 6.31797589e+26 1.38068341e+27 1.20934020e+26
 8.36877979e+23]
iteration : 43
cost 2.5806166622306052e+69
theta:  [-3.30569989e+26 -1.51508267e+27 -1.40411847e+27 -2.03172449e+27
 -9.21479567e+26 -3.02358832e+28 -4.32248854e+28 -2.17009383e+29
 -3.13909415e+27 -6.66569406e+27 -1.45667115e+28 -1.27589784e+27
 -8.82936667e+24]
iteration : 44
cost 2.872488650632903e+71
theta:  [3.48763346e+27 1.59846725e+28 1.48139599e+28 2.14354313e+28
 9.72194415e+27 3.18999551e+29 4.56038242e+29 2.28952781e+30
 3.31185836e+28 7.03254936e+28 1.53684097e+29 1.34611857e+28
 9.31530255e+25]
iteration : 45
cost 3.1973718409160203e+73
theta:  [-3.67957998e+28 -1.68644101e+29 -1.56292657e+29 -2.26151587e+29
 -1.02570042e+29 -3.36556113e+30 -4.81136910e+30 -2.41553501e+31
 -3.49413086e+29 -7.41959502e+29 -1.62142305e+30 -1.42

iteration : 77
cost 9.86069501060561e+138
theta:  [-2.04340964e+61 -9.36544344e+61 -8.67952115e+61 -1.25590512e+62
 -5.69610156e+61 -1.86902312e+63 -2.67193485e+63 -1.34143776e+64
 -1.94042275e+62 -4.12038115e+62 -9.00437416e+62 -7.88692875e+61
 -5.45784964e+59]
iteration : 78
cost 1.0975955832523405e+141
theta:  [2.15587139e+62 9.88088301e+62 9.15721009e+62 1.32502552e+63
 6.00959405e+62 1.97188728e+64 2.81898832e+64 1.41526556e+65
 2.04721648e+63 4.34715178e+63 9.49994181e+63 8.32099632e+62
 5.75822963e+60]
iteration : 79
cost 1.2217354487481074e+143
theta:  [-2.27452263e+63 -1.04246905e+64 -9.66118927e+63 -1.39795005e+64
 -6.34034002e+63 -2.08041271e+65 -2.97413508e+65 -1.49315657e+66
 -2.15988775e+64 -4.58640303e+64 -1.00227837e+65 -8.77895337e+63
 -6.07514142e+61]
iteration : 80
cost 1.3599157371832975e+145
theta:  [2.39970399e+64 1.09984271e+65 1.01929056e+65 1.47488808e+65
 6.68928902e+64 2.19491098e+66 3.13782054e+66 1.57533442e+67
 2.27876003e+65 4.83882179e+65 1.05744009e+66 